### ISSUE TITLE
Please limit the line width to improve readability of the website

### ISSUE THREAD

**Issue by jaxvanyang** [ToshioCP/Gtk4-tutorial#50]
Hi, I found this tutorial very suitable for GTK beginer. But it's not very confortable to read this on the website. Because the line width is beyond 163 characters on a 1080p screen. I use a simple UserCSS to limit the line width:

```css
@-moz-document url-prefix("https://toshiocp.github.io/Gtk4-tutorial") {
    .container {
        max-width: 100ch;
    }
}
```

Now it looks good to me. Could you please consider limiting the line width to improve the readability?
